language: python
before_script:
 - "psql -c 'create database psycopg2_test;' -U postgres"
env:
 - PSYCOPG2_TESTDB_USER=postgres
python:
 - "2.6"
 - "2.7"
 - "3.2"
 - "3.3."
 - "3.4"
 - "pypy"
 - "pypy3"
script: python setup.py test
matrix:
  fast_finish: true
